//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventoEntities : DbContext
    {
        public EventoEntities()
            : base("name=EventoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminDb> AdminDbs { get; set; }
        public virtual DbSet<CompanyDb> CompanyDbs { get; set; }
        public virtual DbSet<FeedbackDb> FeedbackDbs { get; set; }
        public virtual DbSet<PackageDb> PackageDbs { get; set; }
        public virtual DbSet<UserDb> UserDbs { get; set; }
    }
}
