//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class empRegisterView
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int AGE { get; set; }
        public string Gender { get; set; }
        public string CNIC { get; set; }
        public System.DateTime DOB { get; set; }
        public string Contact { get; set; }
        public string Postal_Address { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string UserID { get; set; }
        public bool isApproved { get; set; }
        public bool isActive { get; set; }
    }
}
