//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanStatu
    {
        public int LoanStatusID { get; set; }
        public int ApplicationID { get; set; }
        public double PrincipleAmount { get; set; }
        public double RemainingAmount { get; set; }
        public System.DateTime Tenure { get; set; }
    
        public virtual LoanApplication LoanApplication { get; set; }
    }
}
