//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanApplication()
        {
            this.LoanStatus = new HashSet<LoanStatu>();
        }
    
        public int ApplicationID { get; set; }
        public int LoanID { get; set; }
        public string EmployeeID { get; set; }
        public int PrincipalAmount { get; set; }
        public bool Verified { get; set; }
        public string Reason { get; set; }
        public System.DateTime AppliedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoanStatu> LoanStatus { get; set; }
        public virtual Loan Loan { get; set; }
    }
}
