//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanDetail
    {
        public int LoanDetailID { get; set; }
        public int LoanID { get; set; }
        public string Detail { get; set; }
        public int Category { get; set; }
    
        public virtual Lookup Lookup { get; set; }
        public virtual Loan Loan { get; set; }
    }
}
